version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/api"
      - "/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directories:
      - "/api"
      - "/frontend"
    schedule:
      interval: "weekly"
