import winston from "winston";
import { SendMessageCommand, SQSClient } from "@aws-sdk/client-sqs";
import { RequestImageParams } from "../../types/index.js";
import { ConfigOptions } from "../../config/index.js";
import User from "../../auth/User.js";
import type { CoreCradle } from "../../container/Cradle.js";
import CreateImageMessage from "./CreateImageMessage.js";
import ImageMetadataRepository from "./ImageMetadataRepository.js";

export default class ImageMetadataService {
  private logger: winston.Logger;
  protected config: ConfigOptions;
  protected sqsClient: SQSClient;
  protected user: User;
  protected imageMetadataRepo: ImageMetadataRepository;

  constructor({
    loggerProvider,
    config,
    sqsClient,
    user,
    imageMetadataRepository,
  }: CoreCradle) {
    this.config = config;
    this.sqsClient = sqsClient;
    this.user = user;
    this.imageMetadataRepo = imageMetadataRepository;
    this.logger = loggerProvider.provide("ImageMetadataService");
  }

  /** Submit an image request to the job queue */
  public async publishImageRequest(params: RequestImageParams) {
    const { prompt } = params;

    const imageMetadata = await this.imageMetadataRepo.insert(
      prompt,
      this.user
    );
    const message = new CreateImageMessage(imageMetadata);
    this.logger.info("publishImageRequest", { message });

    const command = new SendMessageCommand({
      QueueUrl: this.config.jobQueueUrl,
      DelaySeconds: 10,
      MessageBody: JSON.stringify(message),
    });

    await this.sqsClient.send(command);
  }

  /** Marks an image as generated by setting the completedAt property. */
  public async markCompleted(imageId: string) {
    await this.imageMetadataRepo.markCompleted(imageId);
  }
}
